# ------------------- Display -------------------
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_FULLSCREEN = False
# SCREEN_WIDTH = 1920
# SCREEN_HEIGHT = 1080
# SCREEN_FULLSCREEN = True

SCREEN_WIDTH_SIXTH = SCREEN_WIDTH / 6
SCREEN_WIDTH_HALF = SCREEN_WIDTH / 2
SCREEN_WIDTH_THIRD = SCREEN_WIDTH / 3
SCREEN_WIDTH_TWFOURTH = SCREEN_WIDTH / 24
SCREEN_HEIGHT_HALF = SCREEN_HEIGHT / 2
SCREEN_HEIGHT_THIRD = SCREEN_HEIGHT / 3
SCREEN_HEIGHT_TWELVETH = SCREEN_HEIGHT / 12

# Subset of the screen space to optimize rendering
SCREEN_RENDERING_RECT_BOARD = (SCREEN_WIDTH_SIXTH - 5, SCREEN_HEIGHT_HALF, 4 * SCREEN_WIDTH_SIXTH + 10, SCREEN_HEIGHT_HALF)
SCREEN_RENDERING_RECT_HEADER = (SCREEN_WIDTH_SIXTH, 0, 4 * SCREEN_WIDTH_SIXTH, SCREEN_HEIGHT_HALF - 1)

# ------------------- Board -------------------
# Difficulty
BOARD_PROGRESS_STEPSIZE = 0.25 # How fast the lines go down
BOARD_PROGRESS_TIME = 400 # How often we read lines

# Lines
BOARD_LINE_POS_SCALER = (SCREEN_WIDTH / 6) / (SCREEN_HEIGHT / 2)
BOARD_LINE_WIDTH = 1
BOARD_LINE_WIDTH_SCALER = 40
BOARD_LINE_SCALER_RATIO = BOARD_LINE_POS_SCALER / BOARD_LINE_WIDTH_SCALER

# Notes
BOARD_NOTE_POS_CLOSE_SCALER = (SCREEN_WIDTH / 24) / (SCREEN_HEIGHT / 2)
BOARD_NOTE_POS_FAR_SCALER = (SCREEN_WIDTH / 8) / (SCREEN_HEIGHT / 2)
BOARD_NOTE_WIDTH = 10
BOARD_NOTE_WIDTH_SCALER = 3
BOARD_NOTE_SCALER_RATIO = BOARD_NOTE_POS_CLOSE_SCALER / BOARD_NOTE_WIDTH_SCALER

# Picks
BOARD_PICK_HEIGHT = SCREEN_HEIGHT - 20
BOARD_PICK_WIDTH = 1.75 * (SCREEN_WIDTH / 24)
BOARD_PICK_WIDTH_HALF = BOARD_PICK_WIDTH / 2

BOARD_REDPICK_START = 5.25 * (SCREEN_WIDTH / 24)
BOARD_REDPICK_END = 7 * (SCREEN_WIDTH / 24)
#BOARD_REDPOINT = (BOARD_REDPICK_START + BOARD_REDPICK_END) / 2

BOARD_GREENPICK_START = 9.125 * (SCREEN_WIDTH / 24)
BOARD_GREENPICK_END = 10.875 * (SCREEN_WIDTH / 24)
#BOARD_GREENPOINT = (BOARD_GREENPICK_START + BOARD_GREENPICK_END) / 2

BOARD_BLUEPICK_START = 13 * (SCREEN_WIDTH / 24)
BOARD_BLUEPICK_END = 14.75 * (SCREEN_WIDTH / 24)
#BOARD_BLUEPOINT = (BOARD_BLUEPICK_START + BOARD_BLUEPICK_END) / 2

BOARD_YELLOWPICK_START = 16.875 * (SCREEN_WIDTH / 24)
BOARD_YELLOWPICK_END = 18.625 * (SCREEN_WIDTH / 24)
#BOARD_YELLOWPOINT = (BOARD_YELLOWPICK_START + BOARD_YELLOWPICK_END) / 2

# ------------------- Game -------------------
GAME_MAXLIVES = 10 # How many times can you miss notes or hit a black note
GAME_USEKEYBOARDINPUT = True
GAME_START_SONG = 'song1.txt'
GAME_IGNORE_MISS = False # Set to True to disable misses
GAME_ENABLE_MUSIC = True

# Audio files
GAME_AUDIO_RED = 'guitar_red1.wav'
GAME_AUDIO_GREEN = 'guitar_green1.wav'
GAME_AUDIO_BLUE = 'guitar_blue1.wav'
GAME_AUDIO_YELLOW = 'guitar_yellow1.wav'
GAME_AUDIO_MISS = 'guitar_miss1.wav'
GAME_AUDIO_MUSIC = 'drum_beat.wav'